// import { getProducts } from "../../pages/api/products";
export default function Shop({ data }) {
    // const products = data.products.edges;
console.log(data)


  return (
    <>
    <h1>shop</h1>
    </>  
    );
}
export const getServerSideProps = async () => {
  const data = await getProducts();

  return {
    props: { data }, 
  };
};















// export default function Shop() {
//     return (
//         <>
//         <h1>shop</h1>
//         </>
//     )
// }




// // This function passes the products as props into the page component.
// // Add the following code to the page component to iterate over and display each product.
// import Head from "next/head";
// import styles from "../styles/Home.module.css";
// import { getProducts } from "../utils/shopify";
// import ProductCard from "../components/ProductCard/ProductCard";

// export default function Home({ data }) {
//   const products = data.products.edges;
//   return (
//     <>
//       <Head>
//         <title>Nextjs Shopify</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         <div className={styles.products}>
//           {products.map((product) => {
//             return <ProductCard key={product.node.id} product={product} />;
//           })}
//         </div>
//       </main>
//     </>
//   );
// }